### ISSUE TITLE
Can't run from plain .js project

### ISSUE THREAD

**Issue by rangedsp** [treban/tradfri-coapdtls#2]
Looks like it's written in coffeeScript?
You might want to compile to js before publishing to npm [https://stackoverflow.com/questions/13645824/can-i-write-npm-package-in-coffeescript](https://stackoverflow.com/questions/13645824/can-i-write-npm-package-in-coffeescript)

```
Jonnys-MBP:ikeaLight jonny$ node main.js 
/Users/jonny/dev/ikeaLight/node_modules/tradfri-coapdtls/tradfri-coapdtls.coffee:1
(function (exports, require, module, __filename, __dirname) { ###
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jonny/dev/ikeaLight/main.js:28:23)
```

**Comment by treban** [comment]
Yeah. You're right. I will merge the pull request. 
And upload this evening a new npm version.
